In [2]:
import pandas as pd
iceCream_data = pd.read_csv('icecreams_sales.csv')
iceCream_data

Temperature (F) Ice Crean Flavor Day of the Week  Sales (in cones)
0                 7        Chocolate          Monday                11
1                 9          Vanilla       Wednesday                27
2                 5       Strawberry          Friday                14
3                10             Mint         Tuesday                 6
4                 9          Vanilla        Thursday                23
5                10       Strawberry       Wednesday                18
6                 9        Chocolate          Friday                 4
7                 7             Mint          Monday                15
8                 5       Strawberry         Tuesday                28
9                 7        Chocolate        Thursday                25
10                5          Vanilla          Monday                12

In [3]:
iceCream_data.shape

(11, 4)

In [4]:
iceCream_data.describe()

Temperature (F)  Sales (in cones)
count        11.000000         11.000000
mean          7.545455         16.636364
std           1.967925          8.273726
min           5.000000          4.000000
25%           6.000000         11.500000
50%           7.000000         15.000000
75%           9.000000         24.000000
max          10.000000         28.000000

In [5]:
iceCream_data.values

array([[7, 'Chocolate', 'Monday', 11],
       [9, 'Vanilla', 'Wednesday', 27],
       [5, 'Strawberry', 'Friday', 14],
       [10, 'Mint', 'Tuesday', 6],
       [9, 'Vanilla', 'Thursday', 23],
       [10, 'Strawberry', 'Wednesday', 18],
       [9, 'Chocolate', 'Friday', 4],
       [7, 'Mint', 'Monday', 15],
       [5, 'Strawberry', 'Tuesday', 28],
       [7, 'Chocolate', 'Thursday', 25],
       [5, 'Vanilla', 'Monday', 12]], dtype=object)

In [6]:
import pandas as pd
iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)']
X

0      7
1      9
2      5
3     10
4      9
5     10
6      9
7      7
8      5
9      7
10     5
Name: Temperature (F), dtype: int64

In [7]:
import pandas as pd
iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)']
y = iceCream_data['Sales (in cones)']
y

0     11
1     27
2     14
3      6
4     23
5     18
6      4
7     15
8     28
9     25
10    12
Name: Sales (in cones), dtype: int64

In [8]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)'].values.reshape(-1, 1)
y = iceCream_data['Sales (in cones)'].values

model = DecisionTreeClassifier()
model.fit(X, y)
iceCream_data

Temperature (F) Ice Crean Flavor Day of the Week  Sales (in cones)
0                 7        Chocolate          Monday                11
1                 9          Vanilla       Wednesday                27
2                 5       Strawberry          Friday                14
3                10             Mint         Tuesday                 6
4                 9          Vanilla        Thursday                23
5                10       Strawberry       Wednesday                18
6                 9        Chocolate          Friday                 4
7                 7             Mint          Monday                15
8                 5       Strawberry         Tuesday                28
9                 7        Chocolate        Thursday                25
10                5          Vanilla          Monday                12

In [9]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)'].values.reshape(-1, 1)
y = iceCream_data['Sales (in cones)'].values

model = DecisionTreeClassifier()
model.fit(X, y)
predictions = model.predict([ [6], [8] ])

predictions

array([12, 11], dtype=int64)

In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)'].values.reshape(-1, 1)
y = iceCream_data['Sales (in cones)'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

score = accuracy_score(y_test, predictions)
score

0.0

In [11]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib

iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)'].values.reshape(-1, 1)
y = iceCream_data['Sales (in cones)'].values

model = DecisionTreeClassifier()
model.fit(X, y)

joblib.dump(model, 'icecreams-sales.joblib')

['icecreams-sales.joblib']

In [12]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib

# iceCream_data = pd.read_csv('icecreams_sales.csv')
# X = iceCream_data['Temperature (F)'].values.reshape(-1, 1)
# y = iceCream_data['Sales (in cones)'].values

# model = DecisionTreeClassifier()
# model.fit(X, y)

model = joblib.load('icecreams-sales.joblib')
predictions = model.predict([ [6], [8] ])
predictions

array([12, 11], dtype=int64)

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

iceCream_data = pd.read_csv('icecreams_sales.csv')
X = iceCream_data['Temperature (F)'].values.reshape(-1, 1)
y = iceCream_data['Sales (in cones)'].values

model = DecisionTreeClassifier()
model.fit(X, y)

class_names = [str(i) for i in sorted(set(y))]
tree.export_graphviz(model, out_file='icecreams-sales.dot',
                    feature_names=['Temperature (F)'],
                    class_names=class_names,
                    label='all',
                    rounded=True,
                    filled=True)